# This file was generated by GoReleaser. DO NOT EDIT.
cask "orvilo" do
  version "0.2.11"

  on_macos do
    on_arm do
      sha256 "3645ce3470219b2de4f899cf8c0fb8b6ab30fdf2046032a2624c9499c69666ce"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "a142df6c763da869c80f9fdb2062b35ecee81902e62b72c59e6283c6e8f2021e"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e998a2f5426fa5aedca65aeb6e30f2bed1aaee748ccd0a9910651e0f62f4bd35"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "1feb9b956cb091cbd86b5738ec004b9598b60c4fd4b66d1995e965935749cf84"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-amd64.tar.gz"
    end
  end

  name "orvilo"
  desc "Orvilo CLI — local agent runtime and management tool for the Orvilo platform"
  homepage "https://github.com/alexj11324/Cordy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orvilo"

  # No zap stanza required
end
