# This file was generated by GoReleaser. DO NOT EDIT.
cask "orvilo" do
  version "0.2.13"

  on_macos do
    on_arm do
      sha256 "08024d45580bf8c769b880c2556145461ef15f3cbc6434a02093e762e34847a7"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "a62d984ef7bc163f66a7e802c694d52b13260e9eec75cd738e33a9f7686c5632"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b2525b10b20a7cd5eac46afa441249387169243ad3af903ba2a907b97a148dd9"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "508e2a6f817e52c3c703ad948e905c8610c17952369afd9fc69315108c5d254a"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-amd64.tar.gz"
    end
  end

  name "orvilo"
  desc "Orvilo CLI — local agent runtime and management tool for the Orvilo platform"
  homepage "https://github.com/alexj11324/Cordy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orvilo"

  # No zap stanza required
end
