# This file was generated by GoReleaser. DO NOT EDIT.
cask "orvilo" do
  version "0.2.12"

  on_macos do
    on_arm do
      sha256 "712d75f1ffd9fac412374105b5314209fc2f0e6875af750e8bbd9393bc0b559e"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "1811e89a1916dc7c2cdbf73615dd67ac02b9d8a14bc8d57c02474cbe532d66e6"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "626e2c4708f1ed6d86a50b11af2ab7e2a44a374f1c2612b81265c17fbf944786"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "481d1364c899efa44d8615aaee99cc900ab86ee450106da8966dbd53c475fd69"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/orvilo-cli-#{version}-linux-amd64.tar.gz"
    end
  end

  name "orvilo"
  desc "Orvilo CLI — local agent runtime and management tool for the Orvilo platform"
  homepage "https://github.com/alexj11324/Cordy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orvilo"

  # No zap stanza required
end
