# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchbay" do
  version "0.2.10"

  on_macos do
    on_arm do
      sha256 "b2679fd4337b1c6a0a38a68148c5f2f46bab708f58ae0ae12a59674ca3d8e6d3"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/patchbay-cli-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "36599205369a308d7cdcbc626dcb1dc0c4f08a351a53a75d84ccf447e402b2db"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/patchbay-cli-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a66e5f032f4f88f387440cd8dd1a2d779fa52592e39449a95938bcbc949e80c0"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/patchbay-cli-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "d2c784ca36b2fba27ea765ff4952b37c4159822ae321b6fd83884094cc98ba98"
      url "https://github.com/alexj11324/Cordy/releases/download/v#{version}/patchbay-cli-#{version}-linux-amd64.tar.gz"
    end
  end

  name "patchbay"
  desc "Patchbay CLI — local agent runtime and management tool for the Patchbay platform"
  homepage "https://github.com/alexj11324/Cordy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchbay"

  # No zap stanza required
end
